# Generated by Django 3.1.2 on 2020-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='details',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
