# Generated by Django 3.1.2 on 2020-10-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201011_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='text',
        ),
    ]
