# Generated by Django 3.1.2 on 2020-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201011_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='test',
            field=models.CharField(default='qw', max_length=2),
        ),
    ]
