# Generated by Django 3.1.2 on 2020-10-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201011_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='test',
            field=models.CharField(max_length=2),
        ),
    ]
